
services:

  data-migrator:
    image: flyway/flyway
    volumes:
      - ./database:/flyway/sql:ro
      - ./modules/api/service-level-tests/db_data_source/test_data_source.sql:/flyway/testdata/V999.0__testdata.sql
    environment:
      FLYWAY_EDITION: community
      FLYWAY_PLACEHOLDERS_logger: ndsa
      FLYWAY_LOCATIONS: filesystem:/flyway/sql,filesystem:/flyway/testdata
    command: -url=jdbc:postgresql://database/ -user=postgres -connectRetries=10 migrate
    depends_on:
      - database

  acceptance-test:
    image: ndsp/acceptance
    build:
      context: ./acceptance
    depends_on:
      - selenium-chrome
      - database
    environment:
      REMOTE_BROWSER_URL: http://selenium-chrome:4444
      DB_HOST: database
      BASE_USER_URL: https://end-user-portal
      BASE_ADMIN_URL: https://admin-portal

  selenium-chrome:
    image: selenium/standalone-chrome

  auth-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.5.1
    ports:
      - 8079:8079
    hostname: auth.docker.internal
    environment:
      SERVER_PORT: 8079
      JSON_CONFIG: |-
        {
          "interactiveLogin": false,
          "tokenCallbacks": [
            {
              "issuerId": "default",
              "tokenExpiry": 120,
              "requestMappings": [
                {
                  "requestParam": "client_id",
                  "match": "*",
                  "claims": {
                    "sub": "testy.mctestface",
                    "email address": "testy.mctestface@nhs.net"
                  }
                }
              ]
            }
          ]
        }

  mock-api:
    image: bbyars/mountebank
    volumes:
      - ./modules/mocks/:/config:ro
    ports:
      - target: 5555
        published: 5555
    entrypoint:
      - mb
      - --configfile
      - /config/mountebank.json

  api:
    image: ndsp/api
    build:
      context: ./modules/api
      dockerfile: ./Dockerfile
    depends_on:
      data-migrator:
        condition: service_completed_successfully
    ports:
      - target: 5002
        published: 5002
    volumes:
      - ./cert:/https:ro
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5002
      ASPNETCORE_Kestrel__Certificates__Default__Password: ndsa
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ConnectionStrings__DefaultConnection: Host=database;Database=postgres;Username=postgres;Include Error Detail=true;

  user-portal:
    image: ndsp/user-portal
    build:
      context: ./source
      dockerfile: ./user.Dockerfile
    depends_on:
      - database
      - api
    ports:
      - target: 443
        published: 5000
    volumes:
      - ./cert:/https:ro
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443
      ASPNETCORE_Kestrel__Certificates__Default__Password: ndsa
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx

      ConnectionStrings__GPConnectEndUserPortal: Host=database;Database=postgres;Username=postgres;Include Error Detail=true;

  end-user-portal:
    image: ndsp/end-user-portal
    build:
      context: ./modules/end-user-portal/
      dockerfile: ./Dockerfile
    depends_on:
      - api
      - mock-api
    ports:
      - target: 443
        published: 5003
    volumes:
      - ./cert:/https:ro
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443
      ASPNETCORE_Kestrel__Certificates__Default__Password: ndsa
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      SiteApi__BaseUrl: http://api:5002
      SupplierApi__BaseUrl: http://mock-api:5555
      OrganizationApi__BaseUrl: http://mock-api:5555
      # API_BASEADDRESS: http://mock-api:5555

  admin-portal:
    image: ndsp/admin-portal
    build:
      context: ./source/
      dockerfile: ./admin.Dockerfile
    working_dir: /app
    depends_on:
      - auth-server
      - database
    ports:
      - target: 443
        published: 5001
    volumes:
      - ./cert:/https:ro
    environment:
      DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: "false"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443
      ASPNETCORE_Kestrel__Certificates__Default__Password: ndsa
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ConnectionStrings__GPConnectEndUserPortal: Host=database;Database=postgres;Username=postgres;Include Error Detail=true;
      Sso__RequireHttpsMetadata: false

  database:
    image: postgres:14
    ports:
      - target: 5432
        published: 5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
