
services:

  api:
    image: ndsp/api
    build:
      context: ./modules/api
      dockerfile: ./Dockerfile
      target: build

  end-user-portal:
    image: ndsp/end-user-portal
    build:
      context: ./modules/end-user-portal
      dockerfile: ./Dockerfile
      target: build
  
  admin-portal:
    image: ndsp/admin-portal
    build:
      context: ./modules/admin-portal
      dockerfile: ./Dockerfile
      target: build
