networks:
  ndsp: {}

services:

  data-migrator:
    image: ndsp/data-migrator
    build:
      context: database
    # volumes:
    #   - ./modules/api/service-level-tests/db_data_source/test_data_source.sql:/flyway/testdata/V999.0__testdata.sql
    environment:
      # FLYWAY_LOCATIONS: filesystem:/flyway/sql,filesystem:/flyway/testdata
      # DO NOT set this in the real deployments, RDS should create this role
      FLYWAY_INIT_SQL: DROP ROLE IF EXISTS rds_iam; CREATE ROLE rds_iam;
    command: -url=jdbc:postgresql://database/ -user=postgres -connectRetries=10 migrate
    depends_on:
      - database
    networks:
      - ndsp

  acceptance-data-migrator:
    image: ndsp/acceptance-data-migrator
    build:
      context: modules/api/service-level-tests/db_data_source
    depends_on:
      data-migrator:
        condition: service_completed_successfully
    networks:
      - ndsp

  acceptance-test:
    image: ndsp/acceptance
    build:
      context: ./acceptance
    depends_on:
      selenium-chrome:
        condition: service_healthy
      database:
        condition: service_healthy
      end-user-portal:
        condition: service_healthy
      acceptance-data-migrator:
        condition: service_completed_successfully
    environment:
      REMOTE_BROWSER_URL: http://selenium-chrome:4444
      DEFAULT_TIMEOUT: "10"
      DB_HOST: database
      BASE_USER_URL: http://end-user-portal
      BASE_ADMIN_URL: https://admin-portal
    networks:
      - ndsp

  selenium-chrome:
    image: selenium/standalone-chrome
    networks:
      - ndsp

  auth-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.5.1
    ports:
      - 8079:8079
    hostname: auth.docker.internal
    environment:
      SERVER_PORT: 8079
      JSON_CONFIG: |-
        {
          "interactiveLogin": false,
          "tokenCallbacks": [
            {
              "issuerId": "default",
              "tokenExpiry": 120,
              "requestMappings": [
                {
                  "requestParam": "client_id",
                  "match": "*",
                  "claims": {
                    "sub": "testy.mctestface",
                    "email address": "testy.mctestface@nhs.net"
                  }
                }
              ]
            }
          ]
        }
    networks:
      - ndsp

  mock-api:
    build:
      context: ./modules/mocks
    ports:
      - target: 5555
        published: 5555
      - target: 5556
        published: 5556
    entrypoint:
      - mb
      - --configfile
      - imposters.ejs
    networks:
      - ndsp

  api:
    image: ndsp/api
    build:
      context: ./modules/api
      dockerfile: ./Dockerfile
    depends_on:
      data-migrator:
        condition: service_completed_successfully
    ports:
      - target: 5002
        published: 5002
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5002
      ConnectionStrings__DefaultConnection: Host=database;Database=postgres;Username=postgres;Include Error Detail=true;
    networks:
      - ndsp

  end-user-portal:
    image: ndsp/end-user-portal
    build:
      context: ./modules/end-user-portal/
      dockerfile: ./Dockerfile
    depends_on:
      - api
      - mock-api
    ports:
      - target: 80
        published: 5003
    environment:
      ASPNETCORE_URLS: http://+:80
      SiteApi__BaseUrl: http://api:5002
      SupplierApi__BaseUrl: http://mock-api:5555
      OrganisationApi__BaseUrl: http://mock-api:5556
      AgreementApi__BaseUrl: http://api:5002
    networks:
      - ndsp

  admin-portal:
    image: ndsp/admin-portal
    build:
      context: ./source/
      dockerfile: ./admin.Dockerfile
    working_dir: /app
    depends_on:
      - auth-server
      - database
    ports:
      - target: 443
        published: 5001
    volumes:
      - ./cert:/https:ro
    environment:
      DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: "false"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443
      ASPNETCORE_Kestrel__Certificates__Default__Password: ndsa
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ConnectionStrings__GPConnectEndUserPortal: Host=database;Database=postgres;Username=postgres;Include Error Detail=true;
      Sso__RequireHttpsMetadata: false
    networks:
      - ndsp

  database:
    image: postgres:14
    ports:
      - target: 5432
        published: 5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - ndsp
