
services:

  data-migrator:
    image: flyway/flyway
    volumes:
      - ./database:/flyway/sql
    environment:
      FLYWAY_EDITION: community
      FLYWAY_PLACEHOLDERS_logger: ndsa
    command: -url=jdbc:postgresql://database/ -user=postgres -password=g3epieC0nnect -connectRetries=10 migrate
    depends_on:
      - database

  auth-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.4.8
    ports:
      - 8080:8080
    hostname: auth.docker.internal
    environment:
      JSON_CONFIG: |-
        {
          "interactiveLogin": false,
          "tokenCallbacks": [
            {
              "issuerId": "default",
              "tokenExpiry": 120,
              "requestMappings": [
                {
                  "requestParam": "client_id",
                  "match": "*",
                  "claims": {
                    "sub": "testy.mctestface",
                    "email address": "testy.mctestface@nhs.net"
                  }
                }
              ]
            }
          ]
        }


  user-portal:
    image: mcr.microsoft.com/dotnet/aspnet
    volumes:
      - ./source/gpconnect-user-portal/bin/Debug/net6.0/publish:/app
    working_dir: /app
    entrypoint: dotnet gpconnect-user-portal.dll
    ports:
      - 5000:80
    environment:
      DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: "false"
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__GPConnectEndUserPortal: Host=database;Database=postgres;Username=postgres;Password=g3epieC0nnect;Include Error Detail=true;

  admin-portal:
    image: mcr.microsoft.com/dotnet/aspnet
    volumes:
      - ./source/gpconnect-user-portal.Admin/bin/Debug/net6.0/publish:/app
    working_dir: /app
    entrypoint: dotnet gpconnect-user-portal.Admin.dll
    ports:
      - 5001:80
    environment:
      DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: "false"
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__GPConnectEndUserPortal: Host=database;Database=postgres;Username=postgres;Password=g3epieC0nnect;Include Error Detail=true;
      Sso__RequireHttpsMetadata: false


  database:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: g3epieC0nnect

  # splunk-server:
  #   image: splunk/splunk
  #   ports:
  #     - 8000:8000
  #     - 8088:8088
  #   environment:
  #     SPLUNK_START_ARGS: --accept-license
  #     SPLUNK_PASSWORD: kersplunk
  #     SPLUNK_HEC_TOKEN: 0E201D4D-3F48-4D5C-A4DE-EEF8B08A198E
  #     SPLUNK_SSL: "False"
