
services:

  data-migrator:
    image: flyway/flyway
    volumes:
      - ./database:/flyway/sql
    environment:
      FLYWAY_EDITION: community
      FLYWAY_PLACEHOLDERS_logger: ndsa
    command: -url=jdbc:postgresql://database/ -user=postgres -password=g3epieC0nnect -connectRetries=10 migrate
    depends_on:
      - database

  auth-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.4.8
    ports:
      - 8080:8080
    hostname: auth.docker.internal
    environment:
      JSON_CONFIG: |-
        {
          "interactiveLogin": false,
          "tokenCallbacks": [
            {
              "issuerId": "default",
              "tokenExpiry": 120,
              "requestMappings": [
                {
                  "requestParam": "client_id",
                  "match": "*",
                  "claims": {
                    "sub": "testy.mctestface",
                    "email address": "testy.mctestface@nhs.net"
                  }
                }
              ]
            }
          ]
        }

  user-portal:
    image: ndsp/user-portal
    build:
      context: ./source
      dockerfile: ./user.Dockerfile
    depends_on:
      - database
      - api
    ports:
      - target: 443
        published: 5000
    volumes:
      - ~/.aspnet/https:/https:ro
    environment:
      DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: "false"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443
      ASPNETCORE_Kestrel__Certificates__Default__Password: d0gp00p
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx

      ConnectionStrings__GPConnectEndUserPortal: Host=database;Database=postgres;Username=postgres;Password=g3epieC0nnect;Include Error Detail=true;

  admin-portal:
    image: ndsp/admin-portal
    build:
      context: ./source
      dockerfile: ./admin.Dockerfile
    working_dir: /app
    depends_on:
      - auth-server
      - database
    ports:
      - 5001:443
    volumes:
      - ~/.aspnet/https:/https:ro
    environment:
      DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: "false"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443
      ASPNETCORE_Kestrel__Certificates__Default__Password: d0gp00p
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ConnectionStrings__GPConnectEndUserPortal: Host=database;Database=postgres;Username=postgres;Password=g3epieC0nnect;Include Error Detail=true;
      Sso__RequireHttpsMetadata: false

  database:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: g3epieC0nnect

  # splunk-server:
  #   image: splunk/splunk
  #   ports:
  #     - 8000:8000
  #     - 8088:8088
  #   environment:
  #     SPLUNK_START_ARGS: --accept-license
  #     SPLUNK_PASSWORD: kersplunk
  #     SPLUNK_HEC_TOKEN: 0E201D4D-3F48-4D5C-A4DE-EEF8B08A198E
  #     SPLUNK_SSL: "False"
