//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpConnect.NationalDataSharingPortal.EndUserPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataFieldNameResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataFieldNameResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GpConnect.NationalDataSharingPortal.EndUserPortal.Resources.DataFieldNameResource" +
                            "s", typeof(DataFieldNameResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCG/ICB Name.
        /// </summary>
        public static string CcgIcbName {
            get {
                return ResourceManager.GetString("CcgIcbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCG/ICB Code.
        /// </summary>
        public static string CcgIcbOdsCode {
            get {
                return ResourceManager.GetString("CcgIcbOdsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Appointment Management.
        /// </summary>
        public static string HasAppointmentManagement {
            get {
                return ResourceManager.GetString("HasAppointmentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Access Record: HTML.
        /// </summary>
        public static string HasHtmlView {
            get {
                return ResourceManager.GetString("HasHtmlView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Send Document.
        /// </summary>
        public static string HasSendDocument {
            get {
                return ResourceManager.GetString("HasSendDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Access Record: Structured.
        /// </summary>
        public static string HasStructured {
            get {
                return ResourceManager.GetString("HasStructured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched.
        /// </summary>
        public static string MatchedCount {
            get {
                return ResourceManager.GetString("MatchedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Name.
        /// </summary>
        public static string ProviderName {
            get {
                return ResourceManager.GetString("ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider ODS Code.
        /// </summary>
        public static string ProviderOdsCode {
            get {
                return ResourceManager.GetString("ProviderOdsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site ODS Code.
        /// </summary>
        public static string SiteOdsCode {
            get {
                return ResourceManager.GetString("SiteOdsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string SitePostcode {
            get {
                return ResourceManager.GetString("SitePostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Case Description.
        /// </summary>
        public static string UseCaseDescription {
            get {
                return ResourceManager.GetString("UseCaseDescription", resourceCulture);
            }
        }
    }
}
