//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpConnect.NationalDataSharingPortal.EndUserPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GpConnect.NationalDataSharingPortal.EndUserPortal.Resources.ErrorMessageResources" +
                            "", typeof(ErrorMessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a value for Clinical Care Organisation Name.
        /// </summary>
        public static string ProviderName {
            get {
                return ResourceManager.GetString("ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a value for ODS Code.
        /// </summary>
        public static string ProviderOdsCode {
            get {
                return ResourceManager.GetString("ProviderOdsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a value for signatory email address.
        /// </summary>
        public static string SignatoryEmail {
            get {
                return ResourceManager.GetString("SignatoryEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a value for signatory name.
        /// </summary>
        public static string SignatoryName {
            get {
                return ResourceManager.GetString("SignatoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a value for signatory role.
        /// </summary>
        public static string SignatoryRole {
            get {
                return ResourceManager.GetString("SignatoryRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a value for Site ODS Code.
        /// </summary>
        public static string SiteOdsCode {
            get {
                return ResourceManager.GetString("SiteOdsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a value for Software Supplier Name.
        /// </summary>
        public static string SoftwareSupplierName {
            get {
                return ResourceManager.GetString("SoftwareSupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a value for GP Connect products.
        /// </summary>
        public static string SoftwareSupplierProduct {
            get {
                return ResourceManager.GetString("SoftwareSupplierProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a value for use case description.
        /// </summary>
        public static string UseCaseDescription {
            get {
                return ResourceManager.GetString("UseCaseDescription", resourceCulture);
            }
        }
    }
}
