apiVersion: batch/v1
kind: Job
metadata:
  name: gpc-ndsp-data-migrate-EPOCHTIME_TO_BE_REPLACED
  namespace: NAMESPACE_TO_BE_REPLACED
spec:
  template:
    spec:
      serviceAccountName: migrate-service-account
      containers:
        - name: migrate
          image: MIGRATE_IMAGE_URL
          imagePullPolicy: Always
          command:
            - bash
            - /flyway/sql/get_secret_and_migrate.sh
            - DATABASE_CREDS_SECRET_ID
          resources:
            requests:
              memory: 64Mi
              cpu: 500m
            limits:
              memory: 128Mi
              cpu: 500m
          env:
            - name: FLYWAY_URL
              value: jdbc:postgresql://DATABASE_ENDPOINT/

      restartPolicy: Never
  backoffLimit: 1
