apiVersion: v1
kind: Namespace
metadata:
  name: NAMESPACE_TO_BE_REPLACED
  labels: 
    ttl: nextmonth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: NAMESPACE_TO_BE_REPLACED
  name: gpc-ndsp-readwrite
rules:
- apiGroups: [ "" ]
  resources: [ "configmaps", "events", "persistentvolumeclaims", "pods", "secrets", "serviceaccounts", "services",  "pods/log", "pods/exec" ]
  verbs: &all_verbs [ "create", "delete", "get", "list", "patch", "update", "watch" ]
- apiGroups: [ "batch" ]
  resources: [ "jobs", "cronjobs" ]
  verbs: *all_verbs
- apiGroups: [ "apps" ]
  resources: [ "deployments", "replicasets", "statefulsets" ]
  verbs: *all_verbs
- apiGroups: [ "networking.k8s.io", "extensions" ]
  resources: [ "ingresses", "networkpolicies" ]
  verbs: *all_verbs
- apiGroups: [ "appmesh.k8s.aws" ]
  resources: [ "meshes", "virtualgateways", "virtualnodes", "virtualrouters", "virtualservices" ]
  verbs: *all_verbs
- apiGroups: [ "" ]
  resources: [ "namespaces" ]
  verbs: [ "delete", "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: NAMESPACE_TO_BE_REPLACED
  name: gpc-ndsp-service-developer-rolebinding
subjects:
- kind: Group
  name: texas:gpc-ndsp-service-developer
roleRef:
  kind: Role
  name: gpc-ndsp-readwrite
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: NAMESPACE_TO_BE_REPLACED
  name: gpc-ndsp-service-jenkins-rolebinding
subjects:
- kind: ServiceAccount
  namespace: gpc-ndsp-jenkins
  name: gpc-ndsp-jenkins
roleRef:
  kind: Role
  name: gpc-ndsp-readwrite
  apiGroup: rbac.authorization.k8s.io
