//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gpconnect_user_portal.DAL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FieldNameResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FieldNameResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gpconnect_user_portal.DAL.Resources.FieldNameResources", typeof(FieldNameResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Management.
        /// </summary>
        public static string Appointment {
            get {
                return ResourceManager.GetString("Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Email Address.
        /// </summary>
        public static string ContactEmailAddress {
            get {
                return ResourceManager.GetString("ContactEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Telephone.
        /// </summary>
        public static string ContactTelephone {
            get {
                return ResourceManager.GetString("ContactTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODS Code.
        /// </summary>
        public static string FormOdsCode {
            get {
                return ResourceManager.GetString("FormOdsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ODS Issued.
        /// </summary>
        public static string NoOdsIssued {
            get {
                return ResourceManager.GetString("NoOdsIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Record: HTML.
        /// </summary>
        public static string RecordAccessHtmlView {
            get {
                return ResourceManager.GetString("RecordAccessHtmlView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Record: Structured.
        /// </summary>
        public static string RecordAccessStructured {
            get {
                return ResourceManager.GetString("RecordAccessStructured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Care Setting.
        /// </summary>
        public static string SelectedCareSetting {
            get {
                return ResourceManager.GetString("SelectedCareSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCG/ICB Name.
        /// </summary>
        public static string SelectedCCGName {
            get {
                return ResourceManager.GetString("SelectedCCGName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCG/ICB ODS Code.
        /// </summary>
        public static string SelectedCCGOdsCode {
            get {
                return ResourceManager.GetString("SelectedCCGOdsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string SelectedSupplier {
            get {
                return ResourceManager.GetString("SelectedSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Name.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Postcode.
        /// </summary>
        public static string SitePostcode {
            get {
                return ResourceManager.GetString("SitePostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Submitter.
        /// </summary>
        public static string Submitter {
            get {
                return ResourceManager.GetString("Submitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Case Description.
        /// </summary>
        public static string UseCaseDescription {
            get {
                return ResourceManager.GetString("UseCaseDescription", resourceCulture);
            }
        }
    }
}
