apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: NAMESPACE_TO_BE_REPLACED
  name: DEPLOYMENT_NAME_TO_BE_REPLACED
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DEPLOYMENT_NAME_TO_BE_REPLACED
  template:
    metadata:
      labels:
        app: DEPLOYMENT_NAME_TO_BE_REPLACED
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: API_CONTAINER_NAME
          image: API_IMAGE_URL
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__DefaultConnection
              value: Host=DATABASE_ENDPOINT;Database=postgres;Username=postgres;Include Error Detail=true;
        - name: END_USER_PORTAL_CONTAINER_NAME
          image: END_USER_PORTAL_IMAGE_URL
          ports:
            - containerPort: 80
