apiVersion: batch/v1
kind: Job
metadata:
  name: gpc-ndsp-data-migrate-EPOCHTIME_TO_BE_REPLACED
  namespace: NAMESPACE_TO_BE_REPLACED
spec:
  template:
    spec:
      serviceAccountName: migrate-service-account
      containers:
        - name: migrate
          image: MIGRATE_IMAGE_URL
          command:
            - "flyway"
            - "-url=jdbc-secretsmanager:postgresql://DATABASE_ENDPOINT/"
            - "-user=DATABASE_CREDS_SECRET_ID"
            - "-connectRetries=10"
            - "migrate"
          resources:
            requests:
              memory: 64Mi
              cpu: 500m
            limits:
              memory: 128Mi
              cpu: 500m

      restartPolicy: Never
  backoffLimit: 1
