apiVersion: v1
kind: Service
metadata:
  name: END_USER_PORTAL_SERVICE_NAME_TO_BE_REPLACED
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: api
  selector:
    app: END_USER_PORTAL_SERVICE_SELECTOR_TO_BE_REPLACED
