//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gpconnect_user_portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataFieldNameResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataFieldNameResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gpconnect_user_portal.Resources.DataFieldNameResources", typeof(DataFieldNameResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Management.
        /// </summary>
        public static string Appointments {
            get {
                return ResourceManager.GetString("Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Management Assurance.
        /// </summary>
        public static string AppointmentsAssurance {
            get {
                return ResourceManager.GetString("AppointmentsAssurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assurance Date.
        /// </summary>
        public static string AssuranceDate {
            get {
                return ResourceManager.GetString("AssuranceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting Assurance.
        /// </summary>
        public static string AwaitingAssurance {
            get {
                return ResourceManager.GetString("AwaitingAssurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer.
        /// </summary>
        public static string Consumer {
            get {
                return ResourceManager.GetString("Consumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We agreed to be bound by the Data Sharing Agreement.
        /// </summary>
        public static string DataSharingAgreementConfirmation {
            get {
                return ResourceManager.GetString("DataSharingAgreementConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address of Information Governance Contact.
        /// </summary>
        public static string DataSharingAgreementContactEmailAddress {
            get {
                return ResourceManager.GetString("DataSharingAgreementContactEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Information Governance Contact.
        /// </summary>
        public static string DataSharingAgreementContactName {
            get {
                return ResourceManager.GetString("DataSharingAgreementContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number of Information Governance Contact.
        /// </summary>
        public static string DataSharingAgreementContactTelephone {
            get {
                return ResourceManager.GetString("DataSharingAgreementContactTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string EndpointChangeStatus {
            get {
                return ResourceManager.GetString("EndpointChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string EndpointChangeSubmitted {
            get {
                return ResourceManager.GetString("EndpointChangeSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Record: HTML Assurance.
        /// </summary>
        public static string HTMLAssurance {
            get {
                return ResourceManager.GetString("HTMLAssurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ODS Issued.
        /// </summary>
        public static string NoOdsIssued {
            get {
                return ResourceManager.GetString("NoOdsIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODS Code.
        /// </summary>
        public static string OdsCode {
            get {
                return ResourceManager.GetString("OdsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Enter the name of the product.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Record: HTML.
        /// </summary>
        public static string RecordAccessHtmlView {
            get {
                return ResourceManager.GetString("RecordAccessHtmlView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Record: Structured.
        /// </summary>
        public static string RecordAccessStructured {
            get {
                return ResourceManager.GetString("RecordAccessStructured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Care Setting.
        /// </summary>
        public static string SelectedCareSetting {
            get {
                return ResourceManager.GetString("SelectedCareSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCG/ICB Name.
        /// </summary>
        public static string SelectedCCGName {
            get {
                return ResourceManager.GetString("SelectedCCGName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCG/ICB (if applicable).
        /// </summary>
        public static string SelectedCCGNameIfApplicable {
            get {
                return ResourceManager.GetString("SelectedCCGNameIfApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCG/ICB ODS Code.
        /// </summary>
        public static string SelectedCCGOdsCode {
            get {
                return ResourceManager.GetString("SelectedCCGOdsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        public static string SelectedSupplier {
            get {
                return ResourceManager.GetString("SelectedSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string SelectedSupplierProduct {
            get {
                return ResourceManager.GetString("SelectedSupplierProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Document.
        /// </summary>
        public static string SendDocument {
            get {
                return ResourceManager.GetString("SendDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Document Assurance.
        /// </summary>
        public static string SendDocumentAssurance {
            get {
                return ResourceManager.GetString("SendDocumentAssurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site ASID.
        /// </summary>
        public static string SiteAsid {
            get {
                return ResourceManager.GetString("SiteAsid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Name.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Party Key.
        /// </summary>
        public static string SitePartyKey {
            get {
                return ResourceManager.GetString("SitePartyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Postcode.
        /// </summary>
        public static string SitePostcode {
            get {
                return ResourceManager.GetString("SitePostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Record: Structured Assurance.
        /// </summary>
        public static string StructuredAssurance {
            get {
                return ResourceManager.GetString("StructuredAssurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Submitter.
        /// </summary>
        public static string Submitter {
            get {
                return ResourceManager.GetString("Submitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Email Address.
        /// </summary>
        public static string SubmitterContactEmailAddress {
            get {
                return ResourceManager.GetString("SubmitterContactEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Contact.
        /// </summary>
        public static string SubmitterContactName {
            get {
                return ResourceManager.GetString("SubmitterContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Telephone.
        /// </summary>
        public static string SubmitterContactTelephone {
            get {
                return ResourceManager.GetString("SubmitterContactTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Enter the name of the individual who is submitting these details.
        /// </summary>
        public static string SubmitterHintText {
            get {
                return ResourceManager.GetString("SubmitterHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Case Description.
        /// </summary>
        public static string UseCaseDescription {
            get {
                return ResourceManager.GetString("UseCaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Enter the use case description of the chosen product.
        /// </summary>
        public static string UseCaseDescriptionHintText {
            get {
                return ResourceManager.GetString("UseCaseDescriptionHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
