//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gpconnect_user_portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportFieldNameResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportFieldNameResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gpconnect_user_portal.Resources.ReportFieldNameResources", typeof(ReportFieldNameResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Management.
        /// </summary>
        public static string Appointments {
            get {
                return ResourceManager.GetString("Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We agreed to be bound by the Data Sharing Agreement.
        /// </summary>
        public static string DataSharingAgreementConfirmation {
            get {
                return ResourceManager.GetString("DataSharingAgreementConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address of Information Governance Contact.
        /// </summary>
        public static string DataSharingAgreementContactEmailAddress {
            get {
                return ResourceManager.GetString("DataSharingAgreementContactEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Information Governance Contact.
        /// </summary>
        public static string DataSharingAgreementContactName {
            get {
                return ResourceManager.GetString("DataSharingAgreementContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number of Information Governance Contact.
        /// </summary>
        public static string DataSharingAgreementContactTelephone {
            get {
                return ResourceManager.GetString("DataSharingAgreementContactTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Management?.
        /// </summary>
        public static string HasAppointment {
            get {
                return ResourceManager.GetString("HasAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Record: HTML?.
        /// </summary>
        public static string HasHtmlView {
            get {
                return ResourceManager.GetString("HasHtmlView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Document?.
        /// </summary>
        public static string HasSendDocument {
            get {
                return ResourceManager.GetString("HasSendDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Record: Structured?.
        /// </summary>
        public static string HasStructured {
            get {
                return ResourceManager.GetString("HasStructured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Appointment Management Enabled?.
        /// </summary>
        public static string IsAppointmentEnabled {
            get {
                return ResourceManager.GetString("IsAppointmentEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Access Record: HTML Enabled?.
        /// </summary>
        public static string IsHtmlEnabled {
            get {
                return ResourceManager.GetString("IsHtmlEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Send Document Enabled?.
        /// </summary>
        public static string IsSendDocumentEnabled {
            get {
                return ResourceManager.GetString("IsSendDocumentEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Access Record: Structured Enabled?.
        /// </summary>
        public static string IsStructuredEnabled {
            get {
                return ResourceManager.GetString("IsStructuredEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ODS Issued.
        /// </summary>
        public static string NoOdsIssued {
            get {
                return ResourceManager.GetString("NoOdsIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODS Code.
        /// </summary>
        public static string OdsCode {
            get {
                return ResourceManager.GetString("OdsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Record: HTML.
        /// </summary>
        public static string RecordAccessHtmlView {
            get {
                return ResourceManager.GetString("RecordAccessHtmlView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Record: Structured.
        /// </summary>
        public static string RecordAccessStructured {
            get {
                return ResourceManager.GetString("RecordAccessStructured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Care Setting.
        /// </summary>
        public static string SelectedCareSetting {
            get {
                return ResourceManager.GetString("SelectedCareSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCG/ICB Name.
        /// </summary>
        public static string SelectedCCGName {
            get {
                return ResourceManager.GetString("SelectedCCGName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCG/ICB (if applicable).
        /// </summary>
        public static string SelectedCCGNameIfApplicable {
            get {
                return ResourceManager.GetString("SelectedCCGNameIfApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCG/ICB ODS Code.
        /// </summary>
        public static string SelectedCCGOdsCode {
            get {
                return ResourceManager.GetString("SelectedCCGOdsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string SelectedSupplier {
            get {
                return ResourceManager.GetString("SelectedSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Document.
        /// </summary>
        public static string SendDocument {
            get {
                return ResourceManager.GetString("SendDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site ASID.
        /// </summary>
        public static string SiteAsid {
            get {
                return ResourceManager.GetString("SiteAsid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Definition ID.
        /// </summary>
        public static string SiteDefinitionId {
            get {
                return ResourceManager.GetString("SiteDefinitionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Definition Status Id.
        /// </summary>
        public static string SiteDefinitionStatusId {
            get {
                return ResourceManager.GetString("SiteDefinitionStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Interactions.
        /// </summary>
        public static string SiteInteractions {
            get {
                return ResourceManager.GetString("SiteInteractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Name.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site ODS Code.
        /// </summary>
        public static string SiteOdsCode {
            get {
                return ResourceManager.GetString("SiteOdsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Party Key.
        /// </summary>
        public static string SitePartyKey {
            get {
                return ResourceManager.GetString("SitePartyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Postcode.
        /// </summary>
        public static string SitePostcode {
            get {
                return ResourceManager.GetString("SitePostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Unique Identifier.
        /// </summary>
        public static string SiteUniqueIdentifier {
            get {
                return ResourceManager.GetString("SiteUniqueIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Submitter.
        /// </summary>
        public static string Submitter {
            get {
                return ResourceManager.GetString("Submitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Email Address.
        /// </summary>
        public static string SubmitterContactEmailAddress {
            get {
                return ResourceManager.GetString("SubmitterContactEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Contact.
        /// </summary>
        public static string SubmitterContactName {
            get {
                return ResourceManager.GetString("SubmitterContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Telephone.
        /// </summary>
        public static string SubmitterContactTelephone {
            get {
                return ResourceManager.GetString("SubmitterContactTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Enter the name of the individual who is submitting these details.
        /// </summary>
        public static string SubmitterHintText {
            get {
                return ResourceManager.GetString("SubmitterHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Case Description.
        /// </summary>
        public static string UseCaseDescription {
            get {
                return ResourceManager.GetString("UseCaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Enter the use case description of the chosen product.
        /// </summary>
        public static string UseCaseDescriptionHintText {
            get {
                return ResourceManager.GetString("UseCaseDescriptionHintText", resourceCulture);
            }
        }
    }
}
